# Definieren der Ports, die geöffnet und zugänglich gemacht werden sollen.
ports:
  - port: 8080
    # Aktion, die beim Start des Dienstes auf diesem Port ausgeführt wird.
    onOpen: open-browser

# Definition der Aufgaben, die beim Start des Workspaces ausgeführt werden.
tasks:
  - name: Setup & Start XTTS
    # 'init' wird nur einmal ausgeführt, wenn der Workspace erstellt wird.
    # Perfekt für das Herunterladen großer Dateien wie unserem Docker-Image.
    init: |
      docker pull aladdin1234/xtts-webui:0.2
    # 'command' wird bei jedem Start des Workspaces ausgeführt.
    # Hier starten wir den eigentlichen Dienst.
    command: |
      docker run -p 8080:8010 --gpus all aladdin1234/xtts-webui:0.2