# Definieren der Ports, die geöffnet und zugänglich gemacht werden sollen.
ports:
  - port: 8080
    # Aktion, die beim Start des Dienstes auf diesem Port ausgeführt wird.
    onOpen: open-browser

# Definition der Aufgaben, die beim Start des Workspaces ausgeführt werden.
tasks:
  - name: Start XTTS WebUI (GPU)
    # 'init' wird nur einmal ausgeführt, um das Start-Skript ausführbar zu machen.
    init: |
      chmod +x ./start_xtts.sh
    # 'command' wird bei jedem Start des Workspaces ausgeführt.
    # Dieses Skript stoppt alte Container, pullt das Image und startet es mit GPU-Unterstützung.
    command: |
      ./start_xtts.sh