# Define the ports to be opened and made accessible.
ports:
  - port: 8080
    # Action to be performed when the service starts on this port.
    onOpen: open-browser

# Definition of tasks to be executed when the workspace starts.
tasks:
  - name: Start XTTS WebUI (GPU)
    # 'command' is executed every time the workspace starts.
    # This script stops old containers, pulls the image, and starts it with GPU support.
    command: |
      ./start_xtts.sh

# Request a GPU-enabled workspace.
# Note: This might require a paid Gitpod plan.
gpu: true
